# Generated by Django 4.2.6 on 2023-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMeterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
