# Generated by Django 4.2.6 on 2024-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverterstate',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
