# Generated by Django 4.2.6 on 2023-10-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powermeterdata',
            name='meter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powermeterdata',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='powermeterdata',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='powermeterdata',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
