# Generated by Django 4.2.6 on 2024-06-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_inverterstate_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverter',
            name='location',
        ),
    ]
