# Generated by Django 4.2.6 on 2023-10-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_powermeterdata_meter_id_alter_powermeterdata_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermeterdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='powermeterdata',
            name='meter_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
