# Generated by Django 4.2.6 on 2023-10-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_powermeterdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermeterdata',
            name='meter_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
