# Generated by Django 4.2.6 on 2024-06-05 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_remove_invertermeasurement_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterAlarm',
            fields=[
                ('alarmID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('activePower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inputPower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internalTemp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('activePowerStatus', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('fault', 'Fault')], default='normal', max_length=10)),
                ('inputPowerStatus', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('fault', 'Fault')], default='normal', max_length=10)),
                ('internalTempStatus', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('fault', 'Fault')], default='normal', max_length=10)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.inverter')),
            ],
        ),
    ]
