# Generated by Django 4.2.6 on 2024-06-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_inverteralarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationMeasurement',
            fields=[
                ('measurementID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('irradiation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('irradiance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.inverter')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('weatherstationid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.site')),
            ],
        ),
    ]
