# Generated by Django 4.2.6 on 2023-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_delete_powermeterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
