# Generated by Django 4.2.6 on 2023-12-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_dailyenergysumm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyEnergySumm',
            new_name='DailyEnergySum',
        ),
    ]
