# Generated by Django 4.2.6 on 2023-12-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_rename_dailyenergysumm_dailyenergysum'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEnergySum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(unique=True)),
            ],
        ),
    ]
