# Generated by Django 4.2.6 on 2023-12-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_monthlyenergysum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyenergysum',
            old_name='month',
            new_name='end_of_month',
        ),
    ]
