# Generated by Django 4.2.6 on 2023-12-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_alter_powermeterdata_meter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total_energy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='powermeterdata',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
