# Generated by Django 4.2.6 on 2023-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_totalenergy_powermeterdata_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('energy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TotalEnergy',
        ),
    ]
