# Generated by Django 4.2.6 on 2023-12-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_hourlyenergy_delete_totalenergy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerMeterData',
        ),
    ]
