# Generated by Django 4.2.6 on 2023-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_powermeterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEnergySumm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_of_day', models.DateTimeField(unique=True)),
            ],
        ),
    ]
