# Generated by Django 4.2.6 on 2024-02-28 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_rename_month_monthlyenergysum_end_of_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('inverterID', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteID', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMeasurements',
            fields=[
                ('siteMeasurementID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activePower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.site')),
            ],
        ),
        migrations.CreateModel(
            name='InverterMeasurement',
            fields=[
                ('measurementID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internalTemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inputPower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gridFrequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('powerFactor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.inverter')),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.site'),
        ),
    ]
