# Generated by Django 4.2.6 on 2024-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_inverter_site_sitemeasurements_invertermeasurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemeasurements',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sitemeasurements',
            name='m_yield',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeasurements',
            name='irradiation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
