# Generated by Django 4.2.6 on 2024-05-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_remove_invertermeasurement_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeasurements',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitemeasurements',
            name='irradiance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitemeasurements',
            name='powerratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitemeasurements',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeasurements',
            name='activePower',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeasurements',
            name='irradiation',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeasurements',
            name='production',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitemeasurements',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
