# Generated by Django 4.2.6 on 2024-05-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_sitemeasurements_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemeasurements',
            old_name='activePower',
            new_name='activepower',
        ),
    ]
