# Generated by Django 4.2.6 on 2024-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0021_inverterstate_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterstate',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
