# Generated by Django 4.2.6 on 2024-05-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0022_alter_inverterstate_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverterstate',
            name='duration',
        ),
    ]
