# Generated by Django 4.2.6 on 2024-05-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0023_remove_inverterstate_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InverterState',
        ),
    ]
