# Generated by Django 4.2.6 on 2023-12-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(default='VN', max_length=255),
        ),
    ]
